### ISSUE TITLE
i cannot get it to work

### ISSUE THREAD

**Issue by 0BAB1** [johannesnoordanus/gcode2image#1]
I tested your project. can't get it to work.

Here is the program i give it as a test : 

G00X0Z0
G00X25Z0
G00X25Z25
G00X0Z25
G00X0Z0

Also : The errors i get depends on the program i give it.

Command and typical errors :

$ python -m gcode2image test.g test

Y_start = round(gc_info['min_Y']/pixelsize)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

S_max = float(gc_info['max_S'])
TypeError: float() argument must be a string or a real number, not 'NoneType'

**Comment by johannesnoordanus** [comment]
Ok, this is due to the fact that your gcode program has no 'writing' commands in it.

Typically you have to add an 'M3' (or 'M4') writing mode gcode, followed by an intensity setting 'S<nr>' (either directly after 'M3' or 'M4' or after the first 'G1' movement command) and use 'G1' write commands to get visible lines.
So you program decodes to:
<code>
G00X0Z0      ; move head to X0 Z0
G00X25Z0     ; move head to X25  (moves head on the X-axis)
G00X25Z25    ; move head to Z25 (moves head up on the Z-axis)
G00X0Z25     ; move head to X0 (moves head back on X-axis)
G00X0Z0      ; moves head to Z0 (moves head down on the Z-axis)
</code>

Note that movement gcode can be written as 'G0' (not 'G00' which is correct but longer) and that movements can be specified minimally to only contain the coordinate(s) that change. 

Another point is that Z coordinates are not supported by gcode2image. The result image <i>.png</i> is 2-D.
I assume you would want to view the movements you specified. To do that I changed the Z coordinates to Y. 
To get the movements visible:
<code>
M4 S300         ; set write mode (constant burn) and intensity
G0 X0Y0         ; move head to X0 Z0
G1 X25          ; move head to X25 and burn with intensity 300 (moves head on the X-axis)
G1 Y25          ; move head to Y25 and burn with intensity 300  (moves head on the Y-axis)
G1 X0           ; move head to X0 and burn with intensity 300  (moves head back on X-axis)
G1 Y0           ; moves head to Y0 and burn with intensity 300 (moves head beck on the Y-axis)
</code>

Make a file 'testje.gc' (for example) and add the above lines.
Run it:
   gcode2image --showimage --flip testje.gc testje.png

This results in a image file 'testje.png' that has the square at the borders (note that <i>gcode2image</i> outputs the minimum number of pixels in X and Y)

If you add the below line at the end of the gcode file, an extra line from (0,0) to the centre of the image will show up. 
This will make it easier to see the result
<code>. 
G1 X12.5Y12.5   ; move head to centre and burn with intensity
</code>

The program should not have shown the errors you reported. It should have shown a warning 'Warning: gcode does not contain write movements: no image produced (use option --showG0 to see movements only)'.
I have fixed that in the upcoming update (very soon).

Regards,
Johannes

**Comment by 0BAB1** [comment]
Hello,

Thank you very much for this detailled response. I will try it out once i'll hop back on my GCODE Project.

I Do not know what you mean by "Writing" though because in my field, M3 and M4 are for spindle controle, maybe you work with 3D Printing manufacturing ?

Anyway, I Am actually supposed to use M3 / M4 even in machinning so... it's my bad.

Thank you once again 👍 

Best regards,
BRH

**Comment by johannesnoordanus** [comment]
Writing means drawing (carving) a line with a certain thickness. 
In CNC this means a tool with a certain diameter drawing (carving) a line from a to b. 
So in gcode:
```
    M4                      ; spindle rotation (right or left) 
    G0 X0 Y0                ; goto (0,0)
    G1 S1000 F10 Z-.1       ; lower the tool bit .1 mm at speed 10
    G1 S1000 F100 X10 Y10   ; write a line at speed 100 with a certain tool (bit) diameter to point (10,10) (in mm)
```

I use this viewer to view results of my other tools used mainly for laser engraving and cutting.
But I do have a CNC machine. For that you need a 3D viewer and 3D gcode (having Z coordinates).
I currently use *LaserWeb* for that. It has a very good 3D viewer and actually shows carving lines. 
A very good program because it is able to do the path calculations.
Note that it is not very easy to use at first.

**Comment by johannesnoordanus** [comment]
I made a update (version 2.3.1) to solve the issues you mentioned.
```pip install -U gcode2image```

**Comment by johannesnoordanus** [comment]
Solved the issues mentioned.
